const API = 'http://localhost:8090/api';
const state = { token: localStorage.getItem('superuser-token'), tab: 'overview', data: null, message: '' };
const permissions = ['PROJECT_ADMIN', 'MANAGE_BRANDING', 'VIEW_USERS', 'MANAGE_CLEARANCE'];

async function request(path, options = {}) {
  const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.message || 'Request failed');
  return payload;
}
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char])); }
function render() { document.querySelector('#app').innerHTML = (state.token ? shell() : login()).replace(/<button class="[^"]*" data-tab="dashboards">Dashboards<\/button>/, '').replace('superuser@udsm.ac.tz', 'superuser@admin.local').replaceAll('UDSM', 'Clearance'); }
function login() { return `<section class="login"><div class="login-panel"><div class="eyebrow">e-CLEARENCE UDSM</div><h1>Superuser control plane</h1><p>Manage the institution configuration and delegated administration from an isolated workspace.</p>${state.message ? `<div class="message">${esc(state.message)}</div>` : ''}<form id="login-form"><div class="field"><label>Email</label><input name="email" type="email" value="superuser@udsm.ac.tz" required></div><div class="field"><label>Password</label><input name="password" type="password" required></div><button class="primary">Sign in securely</button></form></div></section>`; }
function shell() { const b = state.data?.branding || { shortName: 'UDSM' }; return `<div class="shell"><aside class="sidebar"><div class="brand">${esc(b.shortName)}</div><small>Superuser workspace</small><nav class="nav">${[['overview','Overview'],['admins','Sub-admins'],['branding','Branding'],['dashboards','Dashboards']].map(([id,label]) => `<button class="${state.tab === id ? 'active' : ''}" data-tab="${id}">${label}</button>`).join('')}</nav><button class="logout" id="logout">Sign out</button></aside><section class="content">${state.message ? `<div class="message">${esc(state.message)}</div>` : ''}${state.tab === 'overview' ? overview() : state.tab === 'admins' ? admins() : state.tab === 'branding' ? branding() : dashboards()}</section></div>`; }
function overview() { const d = state.data || { dashboards: [], subAdmins: [], branding: {} }; return `<div class="topline"><div><div class="eyebrow">Control centre</div><h1>${esc(d.branding.universityName)}</h1><div class="muted">Configuration changes apply to the connected project through its integration API.</div></div></div><div class="grid"><div class="card"><h3>Sub-admins</h3><div class="metric">${d.subAdmins.length}</div><div class="muted">delegated accounts</div></div><div class="card"><h3>Dashboards</h3><div class="metric">${d.dashboards.filter(x => x.enabled).length}</div><div class="muted">enabled surfaces</div></div><div class="card"><h3>Access model</h3><div class="metric">Scoped</div><div class="muted">permission-based controls</div></div></div><div class="section"><h2>Active configuration</h2><div class="card"><strong>${esc(d.branding.shortName)}</strong><p class="muted">${esc(d.branding.universityName)} · ${d.dashboards.map(x => esc(x.name)).join(' · ')}</p></div></div>`; }
function admins() { const admins = state.data?.subAdmins || []; return `<div class="topline"><div><div class="eyebrow">Delegated access</div><h1>Sub-admins</h1><div class="muted">Each account receives only the permissions selected below.</div></div></div><div class="card"><h2>Create sub-admin</h2><form id="admin-form" class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Temporary password</label><input name="password" type="password" minlength="12" required></div><div class="field full"><label>Permissions</label><div class="checkboxes">${permissions.map(p => `<label class="check"><input type="checkbox" name="permissions" value="${p}"> ${p.replaceAll('_',' ')}</label>`).join('')}</div></div><div><button class="primary">Create sub-admin</button></div></form></div><div class="section"><table class="table"><thead><tr><th>Name</th><th>Email</th><th>Permissions</th><th>Status</th><th></th></tr></thead><tbody>${admins.map(a => `<tr><td>${esc(a.name)}</td><td>${esc(a.email)}</td><td>${a.permissions.map(esc).join(', ') || 'None'}</td><td><span class="pill">${a.active ? 'Active' : 'Suspended'}</span></td><td><button class="danger" data-delete-admin="${a.id}">Delete</button></td></tr>`).join('') || '<tr><td colspan="5" class="muted">No sub-admins created.</td></tr>'}</tbody></table></div>`; }
function branding() { const b = state.data?.branding || {}; const logo = b.logoUrl || '/assets/logo.png'; return `<div class="topline"><div><div class="eyebrow">Project identity</div><h1>Branding</h1><div class="muted">Store project identity as runtime configuration.</div></div></div><div class="card branding-card"><div class="logo-preview"><img src="${esc(logo)}" alt="Project logo" onerror="this.style.display='none'"><span>Current project logo</span></div><form id="branding-form"><div class="field"><label>University name</label><input name="universityName" value="${esc(b.universityName)}" required></div><div class="field"><label>Short name</label><input name="shortName" value="${esc(b.shortName)}" required></div><div class="field"><label>Logo URL</label><input name="logoUrl" value="${esc(b.logoUrl || '/assets/logo.png')}" placeholder="https://... or an approved asset URL"></div><div class="field"><label>Primary color</label><input name="primaryColor" type="color" value="${/^#[0-9a-f]{6}$/i.test(b.primaryColor || '') ? b.primaryColor : '#123c69'}"></div><button class="primary">Save branding</button></form></div>`; }
function dashboards() { const items = state.data?.dashboards || []; return `<div class="topline"><div><div class="eyebrow">Project surfaces</div><h1>Dashboards</h1><div class="muted">Enable, rename, or remove configured dashboard entries.</div></div></div><div class="card"><h2>Add dashboard</h2><form id="dashboard-form" class="form-grid"><div class="field"><label>Identifier</label><input name="id" pattern="[a-z0-9-]+" required></div><div class="field"><label>Name</label><input name="name" required></div><div class="field full"><label>Description</label><textarea name="description" rows="3"></textarea></div><button class="primary">Add dashboard</button></form></div><div class="section grid">${items.map(d => `<div class="card"><h3>${esc(d.name)}</h3><p class="muted">${esc(d.description)}</p><div class="actions"><button class="${d.enabled ? 'primary' : 'danger'}" data-toggle-dashboard="${d.id}">${d.enabled ? 'Enabled' : 'Disabled'}</button><button class="danger" data-delete-dashboard="${d.id}">Delete</button></div></div>`).join('')}</div>`; }
async function refresh() { state.data = await request('/overview'); state.message = ''; render(); }
document.addEventListener('submit', async event => { event.preventDefault(); const form = event.target; try { if (form.id === 'login-form') { const result = await request('/login', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); state.token = result.token; localStorage.setItem('superuser-token', state.token); await refresh(); } else if (form.id === 'admin-form') { const input = Object.fromEntries(new FormData(form)); input.permissions = [...form.querySelectorAll('[name=permissions]:checked')].map(x => x.value); await request('/sub-admins', { method: 'POST', body: JSON.stringify(input) }); state.tab = 'admins'; await refresh(); } else if (form.id === 'branding-form') { await request('/branding', { method: 'PUT', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); await refresh(); state.tab = 'branding'; render(); } else if (form.id === 'dashboard-form') { await request('/dashboards', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form))) }); state.tab = 'dashboards'; await refresh(); } } catch (error) { state.message = error.message; render(); } });
document.addEventListener('click', async event => { const target = event.target; if (target.dataset.tab) { state.tab = target.dataset.tab; state.message = ''; render(); } if (target.id === 'logout') { localStorage.removeItem('superuser-token'); state.token = null; render(); } try { if (target.dataset.deleteAdmin) { await request(`/sub-admins/${target.dataset.deleteAdmin}`, { method: 'DELETE' }); await refresh(); state.tab = 'admins'; render(); } if (target.dataset.deleteDashboard) { await request(`/dashboards/${target.dataset.deleteDashboard}`, { method: 'DELETE' }); await refresh(); state.tab = 'dashboards'; render(); } if (target.dataset.toggleDashboard) { const dashboard = state.data.dashboards.find(d => d.id === target.dataset.toggleDashboard); await request(`/dashboards/${dashboard.id}`, { method: 'PUT', body: JSON.stringify({ enabled: !dashboard.enabled }) }); await refresh(); state.tab = 'dashboards'; render(); } } catch (error) { state.message = error.message; render(); } });
if (state.token) refresh().catch(() => { state.token = null; localStorage.removeItem('superuser-token'); render(); }); else render();
