package com.UDSM.BACKEND.Model;

public enum Role {
    STUDENT,
    DEPARTMENT_OFFICER,
    FINANCE_OFFICER,
    LIBRARY_OFFICER,
    ACCOMMODATION_OFFICER,
    ICT_OFFICER,
    ACADEMIC_STAFF,
    ADMIN
}