package com.UDSM.BACKEND.Model;

public enum Role {
    STUDENT,
    DEPARTMENT_OFFICER,
    FINANCE_OFFICER,
    LIBRARY_OFFICER,
    ACCOMMODATION_OFFICER,
    ICT_OFFICER,        // ← ADD THIS
    ACADEMIC_STAFF,     // ← ADD THIS (or ACADEMIC_STAFF_OFFICER)
    ADMIN
}