import { Routes } from '@angular/router';

import { Login } from './auth/login/login';
import { Register } from './auth/register/register';
import { StudentDashboard } from './dashboard/student/student';
import { LibraryDashboard } from './dashboard/library/library';
import { DepartmentDashboard } from './dashboard/department/department';
import { FinanceDashboard } from './dashboard/finance/finance';
import { IctDashboard } from './dashboard/ict/ict';
import { AcademicDashboard } from './dashboard/academic/academic';
import { AdminDashboard } from './dashboard/admin/admin';
import { ClearanceRequestComponent } from './clearance/request/request';
import { ClearanceStatusComponent } from './clearance/status/status';
import { ClearanceHistoryComponent } from './clearance/history/history';
import { ClearanceReportComponent } from './clearance/report/report';
import { DocumentUploadComponent } from './documents/upload/upload';
import { DocumentsListComponent } from './documents/documents-list/documents-list';
import { NotificationListComponent } from './notifications/notifications';
import { ProfileComponent } from './profile/profile';
import { Landing } from './landing/landing';
import { SignupOptions } from './auth/signup-options/signup-options';
import { StaffRegister } from './auth/staff-register/staff-register';

export const routes: Routes = [
  { path: '', component: Landing },
  { path: 'login', component: Login },
  { path: 'signup-options', component: SignupOptions },
  { path: 'register', component: Register },
  { path: 'staff-register', component: StaffRegister },
  { path: 'dashboard', component: StudentDashboard },
  { path: 'dashboard/library', component: LibraryDashboard },
  { path: 'dashboard/department', component: DepartmentDashboard },
  { path: 'dashboard/finance', component: FinanceDashboard },
  { path: 'dashboard/ict', component: IctDashboard },
  { path: 'dashboard/academic', component: AcademicDashboard },
  { path: 'dashboard/admin', component: AdminDashboard },
  { path: 'clearance/request', component: ClearanceRequestComponent },
  { path: 'clearance/status', component: ClearanceStatusComponent },
  { path: 'clearance/history', component: ClearanceHistoryComponent },
  { path: 'clearance/report', component: ClearanceReportComponent },
  { path: 'documents', component: DocumentsListComponent },
  { path: 'documents/upload', component: DocumentUploadComponent },
  { path: 'notifications', component: NotificationListComponent },
  { path: 'profile', component: ProfileComponent }
];
